export const GENERATE_TURN = 'GENERATE_TURN'
export const CALL_TURN = 'CALL_TURN'
export const SAVE_TURN = 'SAVE_TURN'

export const SEE_CURRENT_TURN = 'SEE_CURRENT_TURN'
export const GO_NEXT_TURN = 'GO_NEXT_TURN'
export const GO_PREVIOUS_TURN = 'GO_PREVIOUS_TURN'

export const ORDER_FREE = 'ORDER_FREE'
export const ORDER_DELIVERY = 'ORDER_DELIVERY'
export const ORDER_WAITING = 'ORDER_WAITING'